name: anitha_s_application5
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  pin_code_fields: ^8.0.1
  google_maps_flutter: ^2.5.0
  intl: ^0.19.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Antic Slab
      fonts: 
        - asset: assets/fonts/AnticSlabRegular.ttf
          weight: 400
    - family: Bigshot One
      fonts: 
        - asset: assets/fonts/BigshotOneRegular.ttf
          weight: 400
    - family: IBM Plex Sans
      fonts: 
        - asset: assets/fonts/IBMPlexSansRegular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSansBold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexSansMedium.ttf
          weight: 500
